language: node_js
sudo: false
node_js:
  - "4.1"
  - "0.12"
  - "0.10"
addons:
  apt:
    packages:
    - libzmq3-dev
    - libprotobuf-dev
    - graphicsmagick
    - rethinkdb
    - yasm
script:
  - gulp build
before_script:
  - npm install -g bower
  - bower install
cache:
  directories:
    - node_modules
    - res/bower_components
notifications:
  slack: openstf:qu01BtEgttJOrGGsRxKBJwki
